// PDF Label Renderer - A4 paper layout for PDF printing
import { LabelData } from '@/components/labels/LabelForm';
import QRCode from 'qrcode';

export async function renderPdfLabel(
  ctx: CanvasRenderingContext2D,
  data: LabelData,
  width: number,
  height: number
): Promise<void> {
  // Clear canvas
  ctx.clearRect(0, 0, width, height);

  // White background (paper)
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, width, height);

  // Page margins (A4 standard)
  const margin = 40;
  const labelWidth = width - (margin * 2);
  const labelHeight = 250;
  const labelY = margin + 50;

  // Paper border
  ctx.strokeStyle = '#e9ecef';
  ctx.lineWidth = 1;
  ctx.strokeRect(0, 0, width, height);

  // Label border
  ctx.strokeStyle = '#212529';
  ctx.lineWidth = 2;
  ctx.strokeRect(margin, labelY, labelWidth, labelHeight);

  // Label content area
  const padding = 20;
  let yPos = labelY + padding + 20;
  const xPos = margin + padding;

  // Title
  ctx.fillStyle = '#212529';
  ctx.font = 'bold 24px Arial';
  ctx.textAlign = 'left';
  ctx.fillText('FOOD LABEL', xPos, yPos);
  yPos += 40;

  // Product name
  ctx.font = 'bold 20px Arial';
  ctx.fillText(data.productName || 'Product Name', xPos, yPos);
  yPos += 30;

  // Category
  if (data.categoryName) {
    ctx.fillStyle = '#6c757d';
    ctx.font = '16px Arial';
    ctx.fillText(data.categoryName, xPos, yPos);
    yPos += 25;
  }

  // Divider
  ctx.strokeStyle = '#dee2e6';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(xPos, yPos);
  ctx.lineTo(margin + labelWidth - padding, yPos);
  ctx.stroke();
  yPos += 20;

  // Info columns
  const col1X = xPos;
  const col2X = xPos + 250;
  let col1Y = yPos;
  let col2Y = yPos;

  // Column 1
  ctx.fillStyle = '#495057';
  ctx.font = '11px Arial';
  ctx.fillText('PREPARED BY:', col1X, col1Y);
  col1Y += 16;
  ctx.fillStyle = '#212529';
  ctx.font = 'bold 14px Arial';
  ctx.fillText(data.preparedByName || 'Unknown', col1X, col1Y);
  col1Y += 25;

  ctx.fillStyle = '#495057';
  ctx.font = '11px Arial';
  ctx.fillText('PREP DATE:', col1X, col1Y);
  col1Y += 16;
  ctx.fillStyle = '#212529';
  ctx.font = 'bold 14px Arial';
  ctx.fillText(data.prepDate || 'N/A', col1X, col1Y);
  col1Y += 25;

  ctx.fillStyle = '#495057';
  ctx.font = '11px Arial';
  ctx.fillText('CONDITION:', col1X, col1Y);
  col1Y += 16;
  ctx.fillStyle = '#212529';
  ctx.font = 'bold 14px Arial';
  ctx.fillText(data.condition || 'N/A', col1X, col1Y);

  // Column 2
  ctx.fillStyle = '#495057';
  ctx.font = '11px Arial';
  ctx.fillText('USE BY:', col2X, col2Y);
  col2Y += 16;
  ctx.fillStyle = '#dc3545';
  ctx.font = 'bold 16px Arial';
  ctx.fillText(data.expiryDate || 'N/A', col2X, col2Y);
  col2Y += 25;

  ctx.fillStyle = '#495057';
  ctx.font = '11px Arial';
  ctx.fillText('QUANTITY:', col2X, col2Y);
  col2Y += 16;
  ctx.fillStyle = '#212529';
  ctx.font = 'bold 14px Arial';
  ctx.fillText(`${data.quantity || '0'} ${data.unit || ''}`, col2X, col2Y);
  col2Y += 25;

  ctx.fillStyle = '#495057';
  ctx.font = '11px Arial';
  ctx.fillText('BATCH #:', col2X, col2Y);
  col2Y += 16;
  ctx.fillStyle = '#212529';
  ctx.font = 'bold 12px monospace';
  ctx.fillText(data.batchNumber || 'N/A', col2X, col2Y);

  // QR code (right side) - Real QR code
  const qrSize = 120;
  const qrX = margin + labelWidth - padding - qrSize;
  const qrY = labelY + padding + 40;
  
  try {
    // Generate QR code data
    const qrData = JSON.stringify({
      productId: data.productId || "",
      productName: data.productName,
      prepDate: data.prepDate,
      expiryDate: data.expiryDate,
      batchNumber: data.batchNumber,
      timestamp: new Date().toISOString(),
    });
    
    // Generate QR code as data URL
    const qrDataUrl = await QRCode.toDataURL(qrData, {
      width: qrSize,
      margin: 1,
      color: {
        dark: '#000000',
        light: '#ffffff'
      }
    });
    
    // Create image and draw it
    const qrImage = new Image();
    qrImage.src = qrDataUrl;
    
    // Wait for image to load
    await new Promise<void>((resolve) => {
      qrImage.onload = () => {
        ctx.drawImage(qrImage, qrX, qrY, qrSize, qrSize);
        resolve();
      };
      qrImage.onerror = () => {
        // Fallback to placeholder
        drawQRPlaceholderPDF(ctx, qrX, qrY, qrSize);
        resolve();
      };
    });
  } catch (error) {
    // Fallback to placeholder
    drawQRPlaceholderPDF(ctx, qrX, qrY, qrSize);
  }

  // Page footer
  ctx.fillStyle = '#adb5bd';
  ctx.font = '10px Arial';
  ctx.textAlign = 'center';
  ctx.fillText('Generated by Food Safe Sync - A4 Label Format', width / 2, height - 20);
  
  // Page number
  ctx.fillText('Page 1 of 1', width / 2, height - 10);
  ctx.textAlign = 'left';
}

function drawQRPlaceholderPDF(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  size: number
): void {
  ctx.strokeStyle = '#dee2e6';
  ctx.lineWidth = 2;
  ctx.strokeRect(x, y, size, size);
  
  ctx.fillStyle = '#adb5bd';
  ctx.font = '12px Arial';
  const prevAlign = ctx.textAlign;
  ctx.textAlign = 'center';
  ctx.fillText('QR CODE', x + size / 2, y + size / 2);
  ctx.textAlign = prevAlign;
}
