// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drvwxrqfrukogharvvrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRydnd4cnFmcnVrb2doYXJ2dnJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzMyMDcsImV4cCI6MjA3MzU0OTIwN30.JDjSd9VxIqiNCM54eKk2CRzK-11DYP441pPDYmQCSN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});